# Dependabot configuration file
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "security"
    # Set review requirements
    reviewers:
      - "freshtechbro"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Allow only security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group dependencies together
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
      production-dependencies:
        patterns:
          - "@modelcontextprotocol/*"
          - "perplexity-api"
          - "axios"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci-cd"
      - "dependencies"
    reviewers:
      - "freshtechbro" 